

import cv2

class DetectionConfig:

    HAND_MAX_NUM_HANDS = 2
    HAND_MIN_DETECTION_CONFIDENCE = 0.7
    HAND_MIN_TRACKING_CONFIDENCE = 0.7

    FACE_MAX_NUM_FACES = 1
    FACE_MIN_DETECTION_CONFIDENCE = 0.7
    FACE_MIN_TRACKING_CONFIDENCE = 0.7

    POSE_MIN_DETECTION_CONFIDENCE = 0.5
    POSE_MIN_TRACKING_CONFIDENCE = 0.5
    POSE_MODEL_COMPLEXITY = 1

    BLINK_EYE_AR_THRESH = 0.25  
    BLINK_EYE_AR_CONSEC_FRAMES = 1  

    THUMB_TIP_IP_DIFF = 0.05
    FINGER_TIP_PIP_DIFF = 0.05

    HEAD_DIRECTION_THRESHOLD = 0.02

    GESTURE_CONFIDENCE_THRESHOLD = 0.7

class DisplayConfig:

    COLOR_HAND = (0, 255, 0)  
    COLOR_FACE = (255, 255, 255)  
    COLOR_POSE = (255, 255, 255)  
    COLOR_TEXT = (255, 255, 255)  
    COLOR_CONNECTION = (255, 255, 255)  

    POSE_MESH_THICKNESS = 2
    POSE_LANDMARK_RADIUS = 3
    POSE_JOINT_RADIUS = 5
    POSE_JOINT_COLOR = (0, 255, 255)

    POSE_HEAD_COLOR = (255, 255, 255)
    POSE_BODY_COLOR = (255, 255, 255)
    POSE_ARM_COLOR = (200, 200, 255)
    POSE_LEG_COLOR = (255, 200, 200)

    FACE_MESH_THICKNESS = 1
    FACE_MESH_LANDMARK_RADIUS = 1
    FACE_MESH_OPACITY = 0.8

    EYE_CONTOUR_COLOR = (0, 255, 255)
    EYE_CONTOUR_THICKNESS = 1

    FONT = cv2.FONT_HERSHEY_SIMPLEX
    FONT_SCALE = 0.6
    THICKNESS = 2

    LANDMARK_RADIUS = 2
    CONNECTION_THICKNESS = 1

class CameraConfig:

    CAMERA_ID = 0
    FRAME_WIDTH = 1280
    FRAME_HEIGHT = 720
    FPS = 30
    MIRROR_IMAGE = True
